version: "3.9"

services:
  tripaura:
    image: postgres:latest
    container_name: tripaura
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - leetlab_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  
volumes:
  leetlab_data:
  qdrant_storage:

